# Site settings
title: VET LIFU LTD
email: info@vetlifu.com
phone: 07866 143896
description: Therapeutic ultrasound An effective treatment for muscle and joint conditions in dogs, cats and horses.
keywords: Therapeutic, Ultrasound, Dogs, Cats, Horses, Muscle, Joint, Treatment
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

menu:
  - title: Home
    url: /
  - title: Questions
    url: /questions
  - title: Our Team
    url: /our_team
  - title: Contact Us
    url: /contact_us



# Footer
footer_summary: In association with HAIFU Medical Technology Co. Ltd


collections:
- questions

# Build settings
markdown: kramdown
